"""Reports: a topic's claims with their evidence, as Markdown, printable
HTML and MediaWiki markup.

What a report may carry is decided per item by its `publish` policy:

- `embed`: may be shown in full (our own screenshots): images become figures.
- `excerpt`: only the bytes a claim rests on, at most MAX_EXCERPT (RAM
  dumps and saves, which contain the game's own code and data).
- `cite`: named with its provenance, never copied (third-party files).
- `never`: named with its provenance, never copied or quoted.
"""

import html
import shutil
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

from evi.vault import Vault

MAX_EXCERPT = 64
STATUS = {"checked": "Checked", "guess": "Guess", "refuted": "Refuted"}


@dataclass
class Source:
    key: str
    name: str
    kind: str
    collection: str
    source: str | None
    author: str | None
    file_time: str | None
    license: str | None
    sha256: str


@dataclass
class Evidence:
    source: Source
    role: str
    detail: str | None
    excerpt: tuple[int, bytes] | None = None  # (offset, bytes)
    figure: str | None = None  # path relative to the report


@dataclass
class Claim:
    id: int
    statement: str
    status: str
    test: str | None
    reference: str | None
    evidence: list[Evidence] = field(default_factory=list)


@dataclass
class Report:
    title: str
    topic: str
    generated_at: str
    claims: list[Claim]
    sources: list[Source]


def _display_name(path: str) -> str:
    # Keep "archive.zip!member" readable, and never expose local directories.
    outer, _, member = path.partition("!")
    name = outer.replace("\\", "/").rsplit("/", 1)[-1]
    return f"{name}!{member}" if member else name


def build(vault: Vault, topic: str, title: str, out_dir: Path) -> Report:
    db = vault.catalog.db
    sources: dict[int, Source] = {}
    claims = []
    (out_dir / "figures").mkdir(parents=True, exist_ok=True)

    for c in db.execute("SELECT * FROM claims WHERE topic = ? ORDER BY id", (topic,)).fetchall():
        claim = Claim(c["id"], c["statement"], c["status"], c["test"], c["reference"])
        for e in db.execute(
            "SELECT e.*, i.* FROM claim_evidence e JOIN items i ON i.id = e.item_id"
            " WHERE e.claim_id = ? ORDER BY CASE e.role WHEN 'supports' THEN 0"
            " WHEN 'contradicts' THEN 1 ELSE 2 END, i.id",
            (c["id"],),
        ).fetchall():
            item_id = e["item_id"]
            if item_id not in sources:
                sources[item_id] = Source(
                    f"S{len(sources) + 1}", _display_name(e["path"]), e["kind"], e["collection"],
                    e["source"], e["author"], e["file_time"], e["license"], e["sha256"],
                )
            ev = Evidence(sources[item_id], e["role"], e["detail"])
            policy = e["publish"]
            if e["offset"] is not None and policy in ("embed", "excerpt"):
                length = min(e["length"] or 16, MAX_EXCERPT)
                data = vault.original(item_id)[e["offset"] : e["offset"] + length]
                ev.excerpt = (e["offset"], data)
            if e["kind"] == "image" and policy == "embed":
                suffix = e["name"].rsplit(".", 1)[-1].lower()
                figure = f"figures/{e['sha256'][:12]}.{suffix}"
                target = out_dir / figure
                if not target.exists():
                    target.write_bytes(vault.original(item_id))
                ev.figure = figure
            claim.evidence.append(ev)
        claims.append(claim)

    return Report(title, topic, datetime.now(UTC).strftime("%Y-%m-%d"), claims, list(sources.values()))


def hexdump(offset: int, data: bytes) -> list[str]:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hexes = " ".join(f"{b:02X}" for b in chunk)
        text = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
        lines.append(f"{offset + i:08X}  {hexes:<47}  {text}")
    return lines


def _counts(report: Report) -> str:
    counts = {s: sum(c.status == s for c in report.claims) for s in STATUS}
    return ", ".join(f"{n} {STATUS[s].lower()}" for s, n in counts.items() if n)


def _provenance(s: Source) -> str:
    parts = [s.kind, f"collection {s.collection}"]
    if s.source:
        parts.append(s.source)
    if s.author:
        parts.append(f"by {s.author}")
    if s.file_time:
        parts.append(f"dated {s.file_time[:10]}")
    if s.license:
        parts.append(f"licence: {s.license}")
    parts.append(f"SHA-256 {s.sha256[:16]}…")
    return "; ".join(parts)


def _intro(report: Report) -> str:
    return (
        f"Generated by Evi on {report.generated_at} from its evidence vault. "
        f"{len(report.claims)} claims ({_counts(report)}). A claim is *checked* when "
        "independent sources agree, or one source agrees with what the running game shows. "
        "Byte excerpts are quoted from RAM dumps at the addresses given; third-party sources "
        "are cited, not copied."
    )


def to_markdown(report: Report) -> str:
    out = [f"# {report.title}", "", _intro(report), ""]
    for c in report.claims:
        out += [f"## {c.statement}", "", f"**{STATUS[c.status]}**" + (f". Reference: {c.reference}" if c.reference else ""), ""]
        if c.test:
            out += [f"*To settle it:* {c.test}", ""]
        for e in c.evidence:
            out.append(f"- [{e.source.key}] {e.source.name}, {e.role}" + (f": {e.detail}" if e.detail else ""))
        out.append("")
        for e in c.evidence:
            if e.excerpt:
                out += [f"[{e.source.key}] bytes at 0x{e.excerpt[0]:X}:", "", "```", *hexdump(*e.excerpt), "```", ""]
            if e.figure:
                out += [f"![[{e.source.key}] {e.detail or e.source.name}]({e.figure})", ""]
    out += ["## Sources", ""]
    out += [f"- **[{s.key}]** {s.name}: {_provenance(s)}" for s in report.sources]
    return "\n".join(out) + "\n"


CSS = """
body { font-family: Georgia, serif; max-width: 52rem; margin: 2rem auto; padding: 0 1rem; color: #1b1b1b; line-height: 1.5; }
h1 { border-bottom: 2px solid #444; } h2 { margin-top: 2.2rem; font-size: 1.2rem; }
.status { display: inline-block; padding: 0 .5rem; border-radius: .3rem; font-family: sans-serif; font-size: .85rem; }
.checked { background: #d7ecd9; } .guess { background: #f6e7c1; } .refuted { background: #f3d0d0; }
pre { background: #f4f4f4; padding: .6rem; overflow-x: auto; font-size: .8rem; }
figure { margin: 1rem 0; } figure img { max-width: 100%; border: 1px solid #ccc; image-rendering: pixelated; }
figcaption, .sources { font-size: .85rem; color: #444; }
@media print { h2 { break-after: avoid; } pre, figure { break-inside: avoid; } }
"""


def to_html(report: Report) -> str:
    esc = html.escape
    out = [f"<!doctype html><html><head><meta charset='utf-8'><title>{esc(report.title)}</title>",
           f"<style>{CSS}</style></head><body>", f"<h1>{esc(report.title)}</h1>", f"<p>{_intro(report)}</p>"]
    for c in report.claims:
        out.append(f"<h2>{esc(c.statement)}</h2>")
        ref = f" Reference: {esc(c.reference)}" if c.reference else ""
        out.append(f"<p><span class='status {c.status}'>{STATUS[c.status]}</span>{ref}</p>")
        if c.test:
            out.append(f"<p><em>To settle it:</em> {esc(c.test)}</p>")
        out.append("<ul>")
        for e in c.evidence:
            detail = f": {esc(e.detail)}" if e.detail else ""
            out.append(f"<li><a href='#{e.source.key}'>[{e.source.key}]</a> {esc(e.source.name)}, {e.role}{detail}</li>")
        out.append("</ul>")
        for e in c.evidence:
            if e.excerpt:
                out.append(f"<p>[{e.source.key}] bytes at 0x{e.excerpt[0]:X}:</p><pre>{esc(chr(10).join(hexdump(*e.excerpt)))}</pre>")
            if e.figure:
                caption = esc(f"[{e.source.key}] {e.detail or e.source.name}")
                out.append(f"<figure><img src='{e.figure}' alt='{caption}'><figcaption>{caption}</figcaption></figure>")
    out.append("<h2>Sources</h2><ul class='sources'>")
    out += [f"<li id='{s.key}'><strong>[{s.key}]</strong> {esc(s.name)}: {esc(_provenance(s))}</li>" for s in report.sources]
    out.append("</ul></body></html>")
    return "\n".join(out)


def to_mediawiki(report: Report) -> str:
    out = [_intro(report), ""]
    for c in report.claims:
        out += [f"== {c.statement} ==", f"'''{STATUS[c.status]}'''" + (f". Reference: {c.reference}" if c.reference else "")]
        if c.test:
            out.append(f"''To settle it:'' {c.test}")
        out += [f"* [{e.source.key}] {e.source.name}, {e.role}" + (f": {e.detail}" if e.detail else "") for e in c.evidence]
        for e in c.evidence:
            if e.excerpt:
                out += [f"[{e.source.key}] bytes at 0x{e.excerpt[0]:X}:", "<pre>", *hexdump(*e.excerpt), "</pre>"]
            if e.figure:
                out.append(f"[[File:{e.figure.rsplit('/', 1)[-1]}|thumb|[{e.source.key}] {e.detail or e.source.name}]]")
        out.append("")
    out += ["== Sources ==", *[f"* '''[{s.key}]''' {s.name}: {_provenance(s)}" for s in report.sources]]
    return "\n".join(out) + "\n"


def write(vault: Vault, topic: str, title: str, out_dir: Path) -> Report:
    if out_dir.exists():
        shutil.rmtree(out_dir / "figures", ignore_errors=True)
    report = build(vault, topic, title, out_dir)
    (out_dir / "report.md").write_text(to_markdown(report))
    (out_dir / "report.html").write_text(to_html(report))
    (out_dir / "report.wiki").write_text(to_mediawiki(report))
    return report
